#!/usr/bin/env python3
"""Execute original x86 bytes and recompiled decompilation on identical inputs.

The oracle is the host CPU, not the lifter or a second copy of its semantics.
Fixtures use the Microsoft x64 argument registers on either supported host.
"""
import argparse
import platform
import re
import struct
import subprocess
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--centrifuge', required=True)
    parser.add_argument('--source-dir', required=True)
    parser.add_argument('--cc', required=True)
    parser.add_argument('--objdump', help='also test leaf functions generated by the C compiler')
    args = parser.parse_args()
    if platform.machine().lower() not in ('amd64', 'x86_64'):
        print('SKIP: original instruction execution requires x86-64')
        return
    # cmp rcx,rdx; conditional branch; return 0 or 1.
    branch = 'b800000000{jump}06b801000000c3c3'
    fixtures = {
        'equal': bytes.fromhex('4839d1' + branch.format(jump='75')),
        'unsigned_less': bytes.fromhex('4839d1' + branch.format(jump='73')),
        'signed_less': bytes.fromhex('4839d1' + branch.format(jump='7d')),
        # MOV changes memory but not flags: the comparison must use the OLD byte.
        'memory_snapshot': bytes.fromhex('4180380041c60001' + branch.format(jump='75')),
        # Likewise an operand register may change after CMP without changing ZF.
        'register_snapshot': bytes.fromhex('4839d148c7c17b000000' + branch.format(jump='75')),
        'byte_register_store': bytes.fromhex('418808b800000000c3'),
        'word_immediate_store': bytes.fromhex('6641c7003412b800000000c3'),
        'dword_immediate_store': bytes.fromhex('41c70078563412b800000000c3'),
        'shift_left64': bytes.fromhex('4889d048d3e0c3'),
        'shift_right64': bytes.fromhex('4889d048d3e8c3'),
        'shift_signed64': bytes.fromhex('4889d048d3f8c3'),
        'shift_left32': bytes.fromhex('89d0d3e0c3'),
        'shift_signed32': bytes.fromhex('89d0d3f8c3'),
        'partial_byte': bytes.fromhex('4889d0b07fc3'),
        'partial_word': bytes.fromhex('4889d066b83412c3'),
        'add32': bytes.fromhex('89d001c8c3'),
        'add_carry64': bytes.fromhex('4801d1' + branch.format(jump='73')),
        'add_overflow64': bytes.fromhex('4801d1' + branch.format(jump='71')),
        'sub_borrow64': bytes.fromhex('4829d1' + branch.format(jump='73')),
        'sub_overflow64': bytes.fromhex('4829d1' + branch.format(jump='71')),
        'add_carry32': bytes.fromhex('01d1' + branch.format(jump='73')),
        'add_overflow32': bytes.fromhex('01d1' + branch.format(jump='71')),
        'adc64': bytes.fromhex('4839d14889c84811d0c3'),
        'sbb64': bytes.fromhex('4839d14889c84819d0c3'),
        'add_carry8': bytes.fromhex('00d1' + branch.format(jump='73')),
        'add_overflow8': bytes.fromhex('00d1' + branch.format(jump='71')),
        'add_carry16': bytes.fromhex('6601d1' + branch.format(jump='73')),
        'add_overflow16': bytes.fromhex('6601d1' + branch.format(jump='71')),
        'inc_preserves_carry': bytes.fromhex('4839d148ffc1' + branch.format(jump='73')),
        'adc32': bytes.fromhex('4839d189c811d0c3'),
        'sbb32': bytes.fromhex('4839d189c819d0c3'),
        'cmov_signed64': bytes.fromhex('4889c84839d1480f4cc2c3'),
        'cmov_unsigned32': bytes.fromhex('89c839d10f42c2c3'),
        'set_signed8': bytes.fromhex('4839d10f9cc00fb6c0c3'),
        'set_unsigned8': bytes.fromhex('4839d10f92c00fb6c0c3'),
        'signed_byte_load': bytes.fromhex('490fbe00c3'),
        'unsigned_word_load': bytes.fromhex('410fb700c3'),
        'signed_word_load': bytes.fromhex('490fbf00c3'),
        'exchange_memory': bytes.fromhex('4889c8498700c3'),
        'xadd_memory': bytes.fromhex('490fc1104889d0c3'),
        'cmpxchg_memory': bytes.fromhex('4889c8490fb110c3'),
        'zero_extend_low8': bytes.fromhex('0fb6c1c3'),
        'sign_extend_low8': bytes.fromhex('480fbec1c3'),
        'zero_extend_high8': bytes.fromhex('4889c80fb6c4c3'),
        'sign_extend_high8': bytes.fromhex('4889c80fbec4c3'),
        # Preserve RSI (nonvolatile in ms_abi) around the string instruction.
        'lodsq_return': bytes.fromhex('4989f24c89c64889d0fc48ad4c89d6c3'),
        'multiply16': bytes.fromhex('4889d0660fafc1c3'),
        'multiply32': bytes.fromhex('89d00fafc1c3'),
    }
    with tempfile.TemporaryDirectory(prefix='centrifuge-x86-roundtrip-') as directory:
        work = Path(directory)
        if args.objdump:
            original_source = work / 'original.c'
            original_source.write_text('''#include <stdint.h>
#define FN __attribute__((ms_abi,noinline)) uint64_t
FN compiler_mix(uint64_t x,uint64_t y,uint8_t *p) { return (x*33+y) ^ (x>>7); }
FN compiler_select(uint64_t x,uint64_t y,uint8_t *p) { return (int64_t)x < (int64_t)y ? x : y; }
FN compiler_narrow(uint64_t x,uint64_t y,uint8_t *p) { return (uint32_t)((uint32_t)x*3+(uint32_t)y); }
FN compiler_alias(uint64_t x,uint64_t y,uint8_t *p) { uint8_t old=p[0]; p[0]=(uint8_t)x; return old==0 ? y : x; }
FN compiler_memory64(uint64_t x,uint64_t y,uint8_t *p) { uint64_t *q=(uint64_t *)p; uint64_t old=*q; *q=x+y; return old ^ *q; }
FN compiler_signed_byte(uint64_t x,uint64_t y,uint8_t *p) { return (int64_t)(int8_t)p[0]; }
FN compiler_conditions(uint64_t x,uint64_t y,uint8_t *p) { p[0]=(x<y); return ((int64_t)x<(int64_t)y)+(x==y)*2; }
''', encoding='utf-8')
            obj = work / 'original.o'
            subprocess.run([args.cc, '-std=gnu11', '-O2', '-fno-stack-protector',
                            '-fno-asynchronous-unwind-tables', '-c', str(original_source), '-o', str(obj)],
                           check=True, timeout=30)
            listing = subprocess.run([args.objdump, '-dr', str(obj)], capture_output=True,
                                     text=True, check=True, timeout=20).stdout
            name = None
            generated = {}
            for line in listing.splitlines():
                label = re.match(r'^\s*[0-9a-fA-F]+ <(compiler_\w+)>:', line)
                if label:
                    name = label.group(1)
                    generated[name] = bytearray()
                elif re.match(r'^\s*[0-9a-fA-F]+ <', line):
                    name = None
                elif name:
                    if re.search(r'\b(?:R_|IMAGE_REL_)', line):
                        raise RuntimeError(f'{name}: relocated code is not a self-contained CPU fixture')
                    instruction = re.match(r'^\s*[0-9a-fA-F]+:\s+((?:[0-9a-fA-F]{2}\s+)+)', line)
                    if instruction:
                        generated[name].extend(bytes.fromhex(instruction.group(1)))
            if len(generated) != 7 or any(not code for code in generated.values()):
                raise RuntimeError('objdump did not provide the seven compiled leaf functions')
            fixtures.update({name: bytes(code) for name, code in generated.items()})
        section_offset = (0x100 + len(fixtures) * 0x80 + 0xfff) & ~0xfff
        payload = bytearray(section_offset + 0x1000)
        addresses = {}
        for index, (name, code) in enumerate(fixtures.items()):
            offset = 0x100 + index * 0x80
            if len(code) > 0x80 or offset + len(code) >= section_offset:
                raise RuntimeError(f'{name}: fixture exceeds reserved code space')
            payload[offset:offset + len(code)] = code
            addresses[name] = 0x400000 + offset
        ident = b'\x7fELF\x02\x01\x01' + bytes(9)
        payload[:64] = struct.pack('<16sHHIQQQIHHHHHH', ident, 2, 62, 1,
                                  addresses['equal'], 64, section_offset, 0, 64, 56, 1, 64, 3, 2)
        payload[64:120] = struct.pack('<IIQQQQQQ', 1, 5, 0, 0x400000,
                                     0x400000, len(payload), len(payload), 0x1000)
        payload[section_offset + 64:section_offset + 128] = struct.pack('<IIQQQQIIQQ', 1, 1, 6, 0x400100,
                                         0x100, len(fixtures) * 0x80, 0, 0, 16, 0)
        names = b'\0.text\0.shstrtab\0'
        names_offset = section_offset + 0x100
        payload[names_offset:names_offset + len(names)] = names
        payload[section_offset + 128:section_offset + 192] = struct.pack('<IIQQQQIIQQ', 7, 3, 0, 0,
                                         names_offset, len(names), 0, 0, 1, 0)
        binary = work / 'fixtures.elf'
        binary.write_bytes(payload)
        source = ['#include <stdint.h>', '#include <stdio.h>', '#include <string.h>',
                  '#ifdef _WIN32', '#include <windows.h>',
                  'static void *executable(size_t n) { return VirtualAlloc(0,n,MEM_COMMIT|MEM_RESERVE,PAGE_EXECUTE_READWRITE); }',
                  '#else', '#include <sys/mman.h>',
                  'static void *executable(size_t n) { void *p=mmap(0,n,PROT_READ|PROT_WRITE|PROT_EXEC,MAP_PRIVATE|MAP_ANONYMOUS,-1,0); return p==MAP_FAILED?0:p; }',
                  '#endif',
                  'typedef uint64_t (__attribute__((ms_abi)) *original_fn)(uint64_t,uint64_t,uint8_t *);']
        for name, code in fixtures.items():
            address = addresses[name]
            result = subprocess.run([args.centrifuge, 'spec',
                                     str(Path(args.source_dir) / 'sleigh/x86-64.slaspec'),
                                     str(binary), 'decompile', hex(address), hex(address + len(code))],
                                    capture_output=True, text=True, timeout=20)
            if result.returncode:
                raise RuntimeError(result.stderr + result.stdout)
            source += [f'static uint64_t recovered_{name}(uint64_t x,uint64_t y,uint8_t *p) {{',
                       'uint64_t rax=0,rbx=0,rcx=x,rdx=y,rsi=0,rdi=0,rsp=0,rbp=0,r8=(uintptr_t)p,r9=0,r10=0,r11=0,r12=0,r13=0,r14=0,r15=0;',
                       'uint64_t param1=0,param2=0,param3=y,param4=x,param5=(uintptr_t)p,param6=0;',
                       'uint8_t r4096=0,r4097=0,r4098=0,r4099=0,r4100=0,r4101=0,r4102=0;',
                       result.stdout, '}']
            source += [f'static const unsigned char code_{name}[]={{' + ','.join(str(b) for b in code) + '};']
        values = [0, 1, 2, 15, 16, 31, 32, 33, 63, 64, 65, 127, 128, 255, 256,
                  0x7fff, 0x8000, 0xffff,
                  0x7fffffff, 0x80000000, 0xffffffff, 0x7fffffffffffffff,
                  0x8000000000000000, 0xffffffffffffffff,
                  0xa5a5a5a5a5a5a500, 0xa5a5a5a5a5a5a5a5]
        source += ['int main(void) {',
                   'uint64_t values[]={' + ','.join(f'{value}ULL' for value in values) + '};']
        for name in fixtures:
            source += ['{', f'fprintf(stderr,"checking {name}\\n");',
                       f'void *mem=executable(sizeof(code_{name})); if(!mem) return 2;',
                       f'memcpy(mem,code_{name},sizeof(code_{name})); original_fn original=(original_fn)mem;',
                       'for(unsigned i=0;i<sizeof(values)/sizeof(values[0]);++i) for(unsigned j=0;j<sizeof(values)/sizeof(values[0]);++j) for(unsigned byte=0;byte<256;++byte) {',
                       'uint64_t amem=0xa5a5a5a5a5a5a500ULL|byte,bmem=amem; uint8_t *a=(uint8_t *)&amem,*b=(uint8_t *)&bmem;',
                       'uint64_t expected=original(values[i],values[j],a);',
                       f'uint64_t actual=recovered_{name}(values[i],values[j],b);',
                       f'if(expected!=actual || amem!=bmem) {{ fprintf(stderr,"{name}: x=%llu y=%llu byte=%u expected=%llu actual=%llu memory=%llu/%llu\\n",(unsigned long long)values[i],(unsigned long long)values[j],byte,(unsigned long long)expected,(unsigned long long)actual,(unsigned long long)amem,(unsigned long long)bmem); return 1; }}',
                       '}', '}']
        source += ['return 0;', '}']
        cfile = work / 'roundtrip.cpp'
        cfile.write_text('\n'.join(source), encoding='utf-8')
        for optimization in ('-O0', '-O2', '-O3'):
            output = work / ('roundtrip' + optimization + '.exe')
            # The native emitter uses C++ auto for simultaneous-write
            # snapshots (ADC/SBB), just like the recovered project output.
            subprocess.run([args.cc, '-x', 'c++', '-std=gnu++17', '-ftrapv',
                            '-Werror=shift-count-overflow', '-Werror=shift-count-negative',
                            optimization, str(cfile), '-o', str(output)], check=True, timeout=30)
            checked = subprocess.run([str(output)], capture_output=True, text=True, timeout=30)
            if checked.returncode:
                raise RuntimeError(f'{optimization}: exit {checked.returncode}\n' + '\n'.join(checked.stderr.splitlines()[-2:]))
            print(f'{optimization}: {len(fixtures) * len(values)**2 * 256} CPU/recompiled return and memory comparisons passed')


if __name__ == '__main__':
    main()
