#!/usr/bin/env python3
"""Generate sleigh/aarch64.slaspec for the centrifuge SLEIGH-lite engine.

All encodings verified empirically against llvm-objdump output of clang
-O2 aarch64-w64-mingw32 binaries (see suite/tools/verify_aarch64_spec.py).

Layout facts established by probing:
  MOVZ/MOVN/MOVK : sf opc2(30:29)=10/00/11 100101(28:23) hw(22:21) imm16 rd
  ADD/SUB imm    : sf op S 10001(28:24) sh(23) imm12(22:10) rn rd
  ADD/SUB sh-reg : sf op S 01011(28:24) shift(23:22) 0(21) rm imm6(15:10) rn rd
  LOG reg        : sf opc2 01010(28:24) shift(23:22) N(21) rm imm6 rn rd
  MADD/MSUB      : sf 00 10111(28:24) op(23) 00(22:21) rm 0(15) ra(14:10) rn rd
  LDR/STR ui     : size(31:30) 111(29:27) 0(26) 1(24) opc(23:22) imm12(21:10) rn rt
  LDR/STR un/pre/post: same but opc(23:22)=00 & bit25=0 & mode(11:10) 00/11/10
  LDP/STP        : size(31:30) 101(29:27) 0(26) 0(25) 1(24) mode(23) 0? L(22)
                   imm7(21:15) rt2(14:10) rn rt ; mode 0=offset 1=pre
                   (scale 4 for w pairs, 8 for x pairs; ldp w uses opc size=00,
                   stp/ldp x size=10)
  B/BL           : 00101/10101(28:24) imm26
  RET            : 11010110010111110000000000(31:5 bits) rn (30 = default)
  CBZ/CBNZ       : sf op(24) 011010(29:24) imm19 rt
  B.cond         : 010101000000000000000(31:5 base, cond at 3:0) imm19
  TBZ/TBNZ       : b5(31) 011011(29:24) op(24)?? -> b5 op 011011 b40 imm14 rt
  ADR/ADRP       : op(31) 10000(28:24) imm19 rd
Single x-register bank; W-form masks with & 0xFFFFFFFF and zext()s the
result (A64 32-bit ops zero-extend).  NZCV = NF VF ZF CF registers.
"""
import re
import sys

OUT = []

def emit(s=""):
    OUT.append(s)

def B(bits):
    return str(int(bits, 2))

def ctor(name, pattern, body):
    pattern = re.sub(r"0b([01]+)", lambda m: B(m.group(1)), pattern)
    emit(f":{name} {pattern} {{ {body} }};")

emit("// aarch64 language module for the centrifuge SLEIGH-lite engine")
emit("// GENERATED by suite/tools/gen_aarch64_spec.py -- do not edit by hand.")
emit("// Base integer ISA + loads/stores + branches, enough for clang -O2")
emit("// C/C++ output.  32-bit forms zero-extend (single x-register bank).")
emit("")
emit("define space ram size=8 type=ram_space default;")
emit("define space regs size=8 type=register_space;")
emit("")
GPRS = [f"x{i}" for i in range(31)] + ["sp"]
emit("define register offset=0 size=8 [")
emit("  " + " ".join(GPRS))
emit("];")
emit("define register offset=4096 size=1 [ NF VF ZF CF ];")
emit("")
emit("token t32 (4) {")
FIELDS = [
    ("sf31", "31:31"), ("op30", "30:30"), ("s29", "29:29"),
    ("opc2", "30:29"),
    ("f28_24", "28:24"), ("f28_23", "28:23"), ("f28_27", "28:27"),
    ("sh23", "23:23"), ("shift2", "23:22"),
    ("op23", "23:23"), ("b24", "24:24"), ("b25", "25:25"), ("b26", "26:26"),
    ("b22", "22:22"), ("b21", "21:21"), ("n21", "21:21"), ("hw", "22:21"),
    ("b15", "15:15"),
    ("imm12", "22:10"), ("imm16", "20:5"), ("immr", "21:16"),
    ("imms", "15:10"), ("imm6", "15:10"), ("imm9", "20:12"),
    ("imm7", "21:15"), ("imm19", "23:5"), ("imm14", "18:5"),
    ("imm26", "25:0"),
    ("rm", "20:16"), ("rn", "9:5"), ("rd", "4:0"),
    ("rt", "4:0"), ("rt2", "14:10"),
    ("size2", "31:30"), ("mode2", "11:10"), ("fx15", "15:5"),
    ("imm3x", "12:10"),
    ("option3", "15:13"), ("sflg", "12:12"),
    ("cond", "3:0"), ("cond4", "15:12"), ("b5", "31:31"), ("b40", "23:19"),
    ("crn", "9:5"),
]
for name, rng in FIELDS:
    emit(f"  {name} = ({rng});")
emit("}")
emit("")
for f in ("rm", "rn", "rd", "rt", "rt2", "crn"):
    emit(f"attach variables [ {f} ] [ {' '.join(GPRS)} ];")
emit("")

# ---------------------------------------------------------------- branches
emit("// ===================== branches / calls / ret =====================")
# B/BL: bits 31:26 = 000101 / 100101.  bit25:0 = imm26.
ctor("b", "target is sf31=0 & op30=0 & s29=0 & f28_27=2 & b26=1 & imm26:target",
     "goto inst_start + sext(target << 2, 28);")
ctor("bl", "target is sf31=1 & op30=0 & s29=0 & f28_27=2 & b26=1 & imm26:target",
     "call inst_start + sext(target << 2, 28);")
# BR/BLR/RET: bits 31:21 base 1101011, bits 22:21 = 00/10/01 resp, bits 20:16=11111
ctor("ret", "is sf31=1 & op30=1 & s29=0 & f28_24=0b10110 & b22=1 & b21=0 & rn=30 & rd=0",
     "goto x30;")
ctor("ret", "rn is sf31=1 & op30=1 & s29=0 & f28_24=0b10110 & b22=1 & b21=0 & rn:rn & rd=0",
     "goto rn;")
ctor("br", "rn is sf31=1 & op30=1 & s29=0 & f28_24=0b10110 & b22=0 & b21=0 & rn:rn & rd=0",
     "goto rn;")
ctor("blr", "rn is sf31=1 & op30=1 & s29=0 & f28_24=0b10110 & b22=0 & b21=1 & rn:rn & rd=0",
     "call rn;")
# CBZ/CBNZ: sf 011010(30:25) op(24) imm19(23:5) Rt
for sf, sfx in ((1, "64"), (0, "32")):
    cmpv = "rt" if sf else "(rt & 0xFFFFFFFF)"
    ctor(f"cbz{sfx}", "rt, target is sf31=%d & op30=0 & s29=1 & f28_27=2 & b26=1 & b25=0 & b24=0 & imm19:target & rt:rt"
         % sf, f"if ({cmpv} == 0) goto inst_start + sext(target << 2, 21);")
    ctor(f"cbnz{sfx}", "rt, target is sf31=%d & op30=0 & s29=1 & f28_27=2 & b26=1 & b25=0 & b24=1 & imm19:target & rt:rt"
         % sf, f"if ({cmpv} != 0) goto inst_start + sext(target << 2, 21);")
CONDS = [
    (0x0, "eq", "ZF != 0"), (0x1, "ne", "ZF == 0"),
    (0x2, "hs", "CF != 0"), (0x3, "lo", "CF == 0"),
    (0x4, "mi", "NF != 0"), (0x5, "pl", "NF == 0"),
    (0x6, "vs", "VF != 0"), (0x7, "vc", "VF == 0"),
    (0x8, "hi", "(CF != 0) & (ZF == 0)"),
    (0x9, "ls", "(CF == 0) | (ZF != 0)"),
    (0xA, "ge", "NF == VF"), (0xB, "lt", "NF != VF"),
    (0xC, "gt", "(ZF == 0) & (NF == VF)"),
    (0xD, "le", "(ZF != 0) | (NF != VF)"),
]
for cv, nm, pred in CONDS:
    ctor(f"b{nm}", "target is sf31=0 & op30=1 & s29=0 & f28_27=2 & b26=1 & b25=0 & b24=0 & imm19:target & cond=%d" % cv,
         f"if ({pred}) goto inst_start + sext(target << 2, 21);")
# TBZ/TBNZ: b5(31) 011011(30:25) op(24) b40(23:19) imm14(18:5) Rt
for bit in range(64):
    b5 = (bit >> 5) & 1
    b40 = bit & 31
    ctor(f"tbz{bit}", "rt, target is b5=%d & f28_24=0b10110 & b40=%d & imm14:target & rt:rt"
         % (b5, b40),
         f"if (((rt >> {bit}) & 1) == 0) goto inst_start + sext(target << 2, 16);")
    ctor(f"tbnz{bit}", "rt, target is b5=%d & f28_24=0b10111 & b40=%d & imm14:target & rt:rt"
         % (b5, b40),
         f"if (((rt >> {bit}) & 1) != 0) goto inst_start + sext(target << 2, 16);")
ctor("nop", "is sf31=1 & op30=1 & s29=0 & f28_23=0b101010 & fx15=256 & rd=31", "")
ctor("clrex", "is sf31=1 & op30=1 & s29=0 & f28_23=0b101010 & fx15=506 & rd=31", "")
ctor("brk", "imm16 is sf31=1 & op30=1 & s29=0 & f28_24=0b10100 & op23=0 & b22=0 & b21=1 & imm16:imm16 & rd=0", "")

# ------------------------------------------------- add/sub (imm & shifted)
emit("")
emit("// ===================== add/sub =====================")
def addsub_imm(sf, op, s, sh, nm):
    sfx = "64" if sf else "32"
    mask = "" if sf else " & 0xFFFFFFFF"
    zext = "" if sf else ", 32"
    im = "(imm << 12)" if sh else "imm"
    res = f"(rn{mask} {'+' if not op else '-'} {im})"
    if s:
        body = (f"rd = zext({res}{zext}); "
                f"ZF = (rd == 0); NF = (rd s< 0); "
                f"CF = (rn s{'>=' if not op else '<'} {im}); "
                f"VF = (((rn ^ {im}) & (rn ^ rd)) s< 0);")
    else:
        body = f"rd = zext({res}{zext});"
    ctor(f"{nm}{sfx}_{'lsl12' if sh else 'imm'}",
         "rd, rn, imm is sf31=%d & op30=%d & s29=%d & f28_24=0b10001 & sh23=%d & imm12:imm & rn:rn & rd:rd"
         % (sf, op, s, sh), body)
# cmp/cmn = subs/adds rd=31 (imm), both widths; must precede addsub_imm
for sf, sfx in ((1, ""), (0, "32")):
    for op, nm in ((1, "cmp"), (0, "cmn")):
        ctor(f"{nm}{sfx}", "rn, imm is sf31=%d & op30=%d & s29=1 & f28_24=0b10001 & sh23=0 & imm12:imm & rn:rn & rd=31" % (sf, op),
             f"ZF = ((rn {'-' if op else '+'} imm) == 0); NF = ((rn {'-' if op else '+'} imm) s< 0);")
# mov (register, to/from sp) alias: add rd, rn, #0 with rn or rd = 31 (sp);
# only when one side is sp -- plain add x, y, #0 stays "add"
ctor("mov", "rd, rn is sf31=1 & op30=0 & s29=0 & f28_24=0b10001 & sh23=0 & imm12=0 & rn=31 & rd:rd",
     "rd = rn;")
ctor("mov", "rd, rn is sf31=1 & op30=0 & s29=0 & f28_24=0b10001 & sh23=0 & imm12=0 & rn:rn & rd=31",
     "rd = rn;")
for sf in (1, 0):
    for op in (0, 1):
        for s in (0, 1):
            for sh in (0, 1):
                nm = {(0, 0): "add", (0, 1): "adds", (1, 0): "sub", (1, 1): "subs"}[(op, s)]
                addsub_imm(sf, op, s, sh, nm)
# cmp/cmn (shifted register): alias of subs/adds with rd=31; must precede subs
SHIFTS = ["lsl", "lsr", "asr"]
for sf in (1, 0):
    for op, nm in ((1, "cmp"), (0, "cmn")):
        for st, snm in enumerate(SHIFTS):
            sh = {"lsl": "<<", "lsr": ">>", "asr": "s>>"}[snm]
            ctor(f"{nm}{'64' if sf else '32'}_{snm}",
                 "rn, rm is sf31=%d & op30=%d & s29=1 & f28_24=0b01011 & shift2=%d & b21=0 & rm:rm & imm6:imm6 & rn:rn & rd=31"
                 % (sf, op, st),
                 f"ZF = ((rn {'-' if op else '+'} (rm {sh} imm6)) == 0); NF = ((rn {'-' if op else '+'} (rm {sh} imm6)) s< 0);")
for sf in (1, 0):
    for op in (0, 1):
        for s in (0, 1):
            for st, snm in enumerate(SHIFTS):
                sfx = "64" if sf else "32"
                mask = "" if sf else " & 0xFFFFFFFF"
                zext = "" if sf else ", 32"
                sh = {"lsl": "<<", "lsr": ">>", "asr": "s>>"}[snm]
                base = f"rm{mask} {sh} imm6"
                nm = {(0, 0): "add", (0, 1): "adds", (1, 0): "sub", (1, 1): "subs"}[(op, s)]
                body = f"rd = zext((rn{mask} {'+' if not op else '-'} {base}){zext});"
                if s:
                    body += " ZF = (rd == 0); NF = (rd s< 0);"
                ctor(f"{nm}{sfx}_{snm}",
                     "rd, rn, rm is sf31=%d & op30=%d & s29=%d & f28_24=0b01011 & shift2=%d & b21=0 & rm:rm & imm6:imm6 & rn:rn & rd:rd"
                     % (sf, op, s, st), body)
# add/sub (extended register): sf op S 01011 00 1 rm option imm3 rn rd
# verified 0x8b37cacc add x22, x22, w23, sxtw #2 (b21=1 distinguishes from shifted)
EXT_OPTS = ((0, "uxtb", "zext(rm, 8)"), (1, "uxth", "zext(rm, 16)"),
            (2, "uxtw", "zext(rm, 32)"), (3, "uxtx", "rm"),
            (4, "sxtb", "sext(rm, 8)"), (5, "sxth", "sext(rm, 16)"),
            (6, "sxtw", "sext(rm, 32)"), (7, "sxtx", "rm"))
for sf in (1, 0):
    sfx = "64" if sf else "32"
    mask = "" if sf else " & 0xFFFFFFFF"
    zext = "" if sf else ", 32"
    opts = [o for o in EXT_OPTS if sf or o[0] < 3]
    imms = range(8) if sf else (0,)
    for op in (0, 1):
        for opt, onm, rexpr in opts:
            for sh3 in imms:
                sign = '+' if not op else '-'
                res = f"(rn{mask} {sign} ({rexpr} << {sh3}))" if sh3 else f"(rn{mask} {sign} {rexpr})"
                # cmp/cmn extended aliases (s=1 rd=31) first
                ctor(f"{'cmp' if op else 'cmn'}{sfx}_x{opt}{sh3}",
                     "rn, rm is sf31=%d & op30=%d & s29=1 & f28_24=0b01011 & shift2=0 & b21=1 & rm:rm & option3=%d & imm3x=%d & rn:rn & rd=31"
                     % (sf, op, opt, sh3),
                     f"ZF = ({res} == 0); NF = ({res} s< 0);")
                for s in (0, 1):
                    nm = {(0, 0): "add", (0, 1): "adds", (1, 0): "sub", (1, 1): "subs"}[(op, s)]
                    body = f"rd = zext({res}{zext});"
                    if s:
                        body += " ZF = (rd == 0); NF = (rd s< 0);"
                    ctor(f"{nm}{sfx}_x{opt}{sh3}",
                         "rd, rn, rm is sf31=%d & op30=%d & s29=%d & f28_24=0b01011 & shift2=0 & b21=1 & rm:rm & option3=%d & imm3x=%d & rn:rn & rd:rd"
                         % (sf, op, s, opt, sh3), body)
emit("")
emit("// ===================== mov family =====================")
for sf in (1, 0):
    maxhw = 4 if sf else 2
    sfx = "64" if sf else "32"
    zext = "" if sf else ", 32"
    for hwv in range(maxhw):
        sh = hwv * 16
        ctor(f"movz{sfx}_hw{hwv}", "rd, imm16 is sf31=%d & opc2=0b10 & f28_23=0b100101 & hw=%d & imm16:imm16 & rd:rd"
             % (sf, hwv), f"rd = zext(imm16 << {sh}{zext});")
        ctor(f"movn{sfx}_hw{hwv}", "rd, imm16 is sf31=%d & opc2=0b00 & f28_23=0b100101 & hw=%d & imm16:imm16 & rd:rd"
             % (sf, hwv), f"rd = zext(~(imm16 << {sh}){zext});")
        if sh == 0:
            ctor(f"movk{sfx}", "rd, imm16 is sf31=%d & opc2=0b11 & f28_23=0b100101 & hw=0 & imm16:imm16 & rd:rd"
                 % sf, "rd = zext(imm16);")
        else:
            ctor(f"movk{sfx}_hw{hwv}", "rd, imm16 is sf31=%d & opc2=0b11 & f28_23=0b100101 & hw=%d & imm16:imm16 & rd:rd"
                 % (sf, hwv),
                 f"rd = (rd & ~({0xFFFF << sh})) | zext(imm16 << {sh}{zext});")

# ------------------------------------------------------- logical (register)
emit("")
emit("// ===================== logical shifted register =====================")
for sf in (1, 0):
    sfx = "64" if sf else "32"
    mask = "" if sf else " & 0xFFFFFFFF"
    zext = "" if sf else ", 32"
    # MOV (register) alias must precede ORR: same encoding with rn=31
    ctor(f"mov{sfx}", "rd, rm is sf31=%d & opc2=0b01 & f28_24=0b01010 & shift2=0 & n21=0 & rm:rm & imm6=0 & rn=31 & rd:rd"
         % sf, f"rd = zext(rm{mask}{zext});")
    for opc2v, opnm, oper in ((0b00, "and", "&"), (0b01, "orr", "|"),
                              (0b10, "eor", "^"), (0b11, "ands", "&")):
        for st, snm in enumerate(SHIFTS):
            sh = {"lsl": "<<", "lsr": ">>", "asr": "s>>"}[snm]
            ctor(f"{opnm}{sfx}_{snm}", "rd, rn, rm is sf31=%d & opc2=%d & f28_24=0b01010 & shift2=%d & n21=0 & rm:rm & imm6:imm6 & rn:rn & rd:rd"
                 % (sf, opc2v, st),
                 f"rd = zext((rn{mask} {oper} (rm{mask} {sh} imm6)){zext});")
            ctor(f"{opnm}n{sfx}_{snm}", "rd, rn, rm is sf31=%d & opc2=%d & f28_24=0b01010 & shift2=%d & n21=1 & rm:rm & imm6:imm6 & rn:rn & rd:rd"
                 % (sf, opc2v, st),
                 f"rd = zext((rn{mask} {oper} ~(rm{mask} {sh} imm6)){zext});")

# ------------------------------------------------------- multiply family
emit("")
emit("// ===================== mul/madd =====================")
for sf in (1, 0):
    sfx = "64" if sf else "32"
    mask = "" if sf else " & 0xFFFFFFFF"
    zext = "" if sf else ", 32"
    base = "sf31=%d & op30=0 & s29=0 & f28_24=0b10111 & b21=0" % sf
    ctor(f"mul{sfx}", "rd, rn, rm is %s & op23=0 & rm:rm & b15=0 & rt2=31 & rn:rn & rd:rd" % base,
         f"rd = zext((rn{mask} * rm{mask}){zext});")
    ctor(f"madd{sfx}", "rd, rn, rm, ra is %s & op23=0 & rm:rm & b15=0 & rt2:ra & rn:rn & rd:rd" % base,
         f"rd = zext((ra{mask} + rn{mask} * rm{mask}){zext});")
    ctor(f"msub{sfx}", "rd, rn, rm, ra is %s & op23=1 & rm:rm & b15=0 & rt2:ra & rn:rn & rd:rd" % base,
         f"rd = zext((ra{mask} - rn{mask} * rm{mask}){zext});")
    ctor(f"neg{sfx}", "rd, rm is %s & op23=0 & rm:rm & b15=0 & rt2=31 & rn=31 & rd:rd" % base,
         f"rd = zext(-(rm{mask}){zext});")
# long multiply-add/sub (32x32 -> 64): sf 00 11011 op23 U 1 rm 0 ra rn rd
# verified 0x9b287c08 smull x8, w0, w8 (f28_24=27, b21=1, ra=31)
LONG = ((0, 0, "smaddl", "sext(rn & 0xFFFFFFFF, 32) * sext(rm & 0xFFFFFFFF, 32) + ra"),
        (0, 1, "umaddl", "zext(rn & 0xFFFFFFFF, 32) * zext(rm & 0xFFFFFFFF, 32) + ra"),
        (1, 0, "smsubl", "sext(rn & 0xFFFFFFFF, 32) * sext(rm & 0xFFFFFFFF, 32) - ra"),
        (1, 1, "umsubl", "zext(rn & 0xFFFFFFFF, 32) * zext(rm & 0xFFFFFFFF, 32) - ra"))
for sub, u, nm, expr in LONG:
    base = ("sf31=1 & op30=0 & s29=0 & f28_24=0b11011 & op23=%d & b22=%d & b21=1 & rm:rm & b15=0"
            % (sub, u))
    ctor(nm, "rd, rn, rm, ra is %s & rt2:ra & rn:rn & rd:rd" % base,
         f"rd = {expr};")
    if not sub:
        ctor("smull" if not u else "umull",
             "rd, rn, rm is %s & rt2=31 & rn:rn & rd:rd" % base,
             f"rd = {expr.replace(' + ra', '')};")

# ------------------------------------------------- loads/stores (imm forms)
emit("")
emit("// ===================== loads/stores =====================")
SIZES = {0b11: ("x", 8, ""), 0b10: ("w", 4, ", 32"),
         0b01: ("h", 2, ", 16"), 0b00: ("b", 1, ", 8")}
for sz, (sfx, nbytes, zext) in SIZES.items():
    shift = nbytes.bit_length() - 1
    common = "size2=%d & s29=1 & f28_27=3 & b26=0 & b25=0 & b24=1 & op23=0" % sz
    ctor(f"str{sfx}_ui", "rt, rn, imm12 is %s & b22=0 & imm12:imm12 & rn:rn & rt:rt" % common,
         f"*(rn + (imm12 << {shift})) = zext(rt{zext});")
    ctor(f"ldr{sfx}_ui", "rt, rn, imm12 is %s & b22=1 & imm12:imm12 & rn:rn & rt:rt" % common,
         f"rt = zext(load(rn + (imm12 << {shift}), {nbytes}){zext});")
    for b24v, mode, mn in ((0, 0b00, "ur"), (0, 0b01, "po"), (0, 0b11, "pr")):
        mcommon = ("size2=%d & s29=1 & f28_27=3 & b26=0 & b25=0 & b24=%d & op23=0"
                   " & imm9:imm9 & mode2=%d" % (sz, b24v, mode))
        if mn == "pr":
            st_body = f"rn = rn + sext(imm9, 9); *(rn) = zext(rt{zext});"
            ld_body = f"rn = rn + sext(imm9, 9); rt = zext(load(rn, {nbytes}){zext});"
        elif mn == "po":
            st_body = f"*(rn) = zext(rt{zext}); rn = rn + sext(imm9, 9);"
            ld_body = f"rt = zext(load(rn, {nbytes}){zext}); rn = rn + sext(imm9, 9);"
        else:
            st_body = f"*(rn + sext(imm9, 9)) = zext(rt{zext});"
            ld_body = f"rt = zext(load(rn + sext(imm9, 9), {nbytes}){zext});"
        ctor(f"str{sfx}_{mn}i", "rt, rn, imm9 is %s & b22=0 & rn:rn & rt:rt" % mcommon, st_body)
        ctor(f"ldr{sfx}_{mn}i", "rt, rn, imm9 is %s & b22=1 & rn:rn & rt:rt" % mcommon, ld_body)
# sign-extending loads (opc=10): ldrsb/ldrsh/ldrsw -> x
for sz, sfx, nbytes in ((0b00, "sb", 1), (0b01, "sh", 2), (0b10, "sw", 4)):
    shift = nbytes.bit_length() - 1
    common = "size2=%d & s29=1 & f28_27=3 & b26=0 & b25=0 & b24=1" % sz
    ctor(f"ldr{sfx}x_ui", "rt, rn, imm12 is %s & op23=1 & b22=0 & imm12:imm12 & rn:rn & rt:rt" % common,
         f"rt = sext(load(rn + (imm12 << {shift}), {nbytes}), {nbytes*8});")

# ------------------------------------------- register-offset ldr/str
emit("")
emit("// ===================== ldr/str register-offset =====================")
# size2 111(29:27) 0(26) 0(25) 0(24) opc(23:22)=0L 1(21) rm option(15:13) S(12) 10(11:10) rn rt
# verified 0xb8757a88 ldr w8,[x20,x21,lsl#2]: f28_27=3 b26=0 b25=0 b24=0 b21=1 mode2=2
OPT = ((0b010, "uxtw", "zext(rm, 32)"),
       (0b011, "lsl",  "rm"),
       (0b110, "sxtw", "sext(rm, 32)"))
for sz, (sfx, nbytes, zext) in SIZES.items():
    shift = nbytes.bit_length() - 1
    base = ("size2=%d & s29=1 & f28_27=3 & b26=0 & b25=0 & b24=0 & op23=0 & b21=1"
            " & rm:rm & mode2=2 & rn:rn & rt:rt" % sz)
    for opt, onm, rexpr in OPT:
        for sflg in (0, 1):
            sh = sflg << shift
            off = f"({rexpr} << {sh})" if sh else rexpr
            ctor(f"str{sfx}_{onm}{sh}", "rt, rn, rm is %s & option3=%d & sflg=%d & b22=0"
                 % (base, opt, sflg),
                 f"*(rn + {off}) = zext(rt{zext});")
            ctor(f"ldr{sfx}_{onm}{sh}", "rt, rn, rm is %s & option3=%d & sflg=%d & b22=1"
                 % (base, opt, sflg),
                 f"rt = zext(load(rn + {off}, {nbytes}){zext});")
# sign-extending register-offset loads (ldrsw/ldrsh/ldrsb -> x)
for sz, sfx, nbytes in ((0b00, "sb", 1), (0b01, "sh", 2), (0b10, "sw", 4)):
    shift = nbytes.bit_length() - 1
    base = ("size2=%d & s29=1 & f28_27=3 & b26=0 & b25=0 & b24=0 & op23=1 & b22=0 & b21=1"
            " & rm:rm & mode2=2 & rn:rn & rt:rt" % sz)
    for opt, onm, rexpr in OPT:
        for sflg in (0, 1):
            sh = sflg << shift
            off = f"({rexpr} << {sh})" if sh else rexpr
            ctor(f"ldr{sfx}x_{onm}{sh}", "rt, rn, rm is %s & option3=%d & sflg=%d"
                 % (base, opt, sflg),
                 f"rt = sext(load(rn + {off}, {nbytes}), {nbytes*8});")

# ------------------------------------------------- bitfield (sxtw/uxtw/...)
emit("")
emit("// ===================== bitfield moves =====================")
# SBFM: sf 00 100110(28:23) N 0 immr imms rn rd ; UBFM: sf 10 100110 -> f28_24=19
# sxtw/sxth/sxtb = SBFM immr=0 imms=31/15/7 ; uxtw/uxth/uxtb = UBFM immr=0 imms=31/15/7
for sf, sfx, zext in ((1, "64", ""), (0, "32", ", 32")):
    mask = "" if sf else " & 0xFFFFFFFF"
    ctor(f"sxtw{sfx}", "rd, rn is sf31=%d & opc2=0b00 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=31 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(sext(rn{mask}, 32){zext});")
    ctor(f"sxth{sfx}", "rd, rn is sf31=%d & opc2=0b00 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=15 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(sext(rn{mask}, 16){zext});")
    ctor(f"sxtb{sfx}", "rd, rn is sf31=%d & opc2=0b00 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=7 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(sext(rn{mask}, 8){zext});")
    ctor(f"uxtw{sfx}", "rd, rn is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=31 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(rn{mask} & 0xFFFFFFFF{zext});")
    ctor(f"uxth{sfx}", "rd, rn is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=15 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(rn{mask} & 0xFFFF{zext});")
    ctor(f"uxtb{sfx}", "rd, rn is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & b21=0 & immr=0 & imms=7 & rn:rn & rd:rd"
         % (sf, sf), f"rd = zext(rn{mask} & 0xFF{zext});")
# asr/lsr immediate aliases (imms = width-1: amount lives in immr alone)
for sf, sfx, zext, mask, ms in ((1, "64", "", "", 63), (0, "32", ", 32", " & 0xFFFFFFFF", 31)):
    ctor(f"asr{sfx}", "rd, rn, immr is sf31=%d & opc2=0b00 & f28_24=0b10011 & b22=%d & immr:immr & imms=%d & rn:rn & rd:rd"
         % (sf, sf, ms), f"rd = zext((rn{mask} s>> immr){zext});")
    ctor(f"lsr{sfx}", "rd, rn, immr is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & immr:immr & imms=%d & rn:rn & rd:rd"
         % (sf, sf, ms), f"rd = zext((rn{mask} >> immr){zext});")
# lsl immediate = ubfm with imms == 63-amount (constrained per amount)
for sf, sfx, zext, bits in ((1, "64", "", 64), (0, "32", ", 32", 32)):
    for amt in range(1, bits):
        ctor(f"lsl{sfx}_a{amt}", "rd, rn is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & immr=%d & imms=%d & rn:rn & rd:rd"
             % (sf, sf, bits - amt, bits - 1 - amt),
             f"rd = zext((rn << {amt}){zext});")

# generic sbfm/ubfm fallback (32/64, any immr/imms) -- b21 is immr's top bit.
# MUST stay after the asr/lsr/lsl aliases above so the aliases win on name.
for sf, sfx, zext in ((1, "64", ""), (0, "32", ", 32")):
    mask = "" if sf else " & 0xFFFFFFFF"
    ctor(f"sbfm{sfx}", "rd, rn, immr, imms is sf31=%d & opc2=0b00 & f28_24=0b10011 & b22=%d & immr:immr & imms:imms & rn:rn & rd:rd"
         % (sf, sf),
         f"rd = zext(sext((rn{mask} >> immr) << (63 - imms), 64){zext});")
    ctor(f"ubfm{sfx}", "rd, rn, immr, imms is sf31=%d & opc2=0b10 & f28_24=0b10011 & b22=%d & immr:immr & imms:imms & rn:rn & rd:rd"
         % (sf, sf),
         f"rd = zext(((rn{mask} << (63 - imms)) >> (63 - imms + immr)){zext});")

# ------------------------------------------------- conditional select
emit("")
emit("// ===================== csel family =====================")
# sf 00 11010100 0(23) rm cond(15:12) op(11:10) 0? rn rd ; verified 0x1a89c10b
COPS = [(0b00, "csel", "{a}", "{b}"),
        (0b01, "csinc", "{a}", "({b} + 1)"),
        (0b10, "csinv", "~{a}", "{b}"),
        (0b11, "csneg", "(-{a})", "{b}")]
for sf, sfx, zext, mask in ((1, "64", "", ""), (0, "32", ", 32", " & 0xFFFFFFFF")):
    for opv, nm, ta, tb in COPS:
        for cv, cnm, pred in CONDS:
            aval = ta.format(a=f"(rn{mask})", b=f"(rm{mask})")
            bval = tb.format(a=f"(rn{mask})", b=f"(rm{mask})")
            ctor(f"{nm}{sfx}_{cnm}",
                 "rd, rn, rm is sf31=%d & op30=0 & s29=0 & f28_24=0b11010 & op23=1 & b22=0 & b21=0 & rm:rm & cond4=%d & mode2=%d & rn:rn & rd:rd"
                 % (sf, cv, opv),
                 f"rd = zext(select({pred}, {aval}, {bval}){zext});")

# ------------------------------------------------- load/store exclusive
emit("")
emit("// ===================== load/store exclusive =====================")
# verified: ldaxr c85ffea8 = size2 0(29) 1000(28:24) 0(23) 1(22) 0(21) 11111 imm 111111 mode 3
for sz, sfx, nbytes, zext in ((0b11, "x", 8, ""), (0b10, "w", 4, ", 32")):
    ctor(f"ldaxr{sfx}", "rt, rn is size2=%d & s29=0 & f28_24=0b01000 & op23=0 & b22=1 & b21=0 & rt2=31 & b15=1 & mode2=3 & rn:rn & rt:rt"
         % sz, f"rt = zext(load(rn, {nbytes}){zext});")
    ctor(f"stlxr{sfx}", "rs, rt, rn is size2=%d & s29=0 & f28_24=0b01000 & op23=0 & b22=0 & b21=0 & rt2:rs & b15=1 & mode2=3 & rn:rn & rt:rt"
         % sz, f"*(rn) = zext(rt{zext}); rs = 0;")

# ------------------------------------------------- ldp/stp
emit("")
emit("// ===================== ldp/stp =====================")
# size(31:30) 101(29:27) 0(26) 0(25) | b24 b23 L(22) imm7(21:15) rt2 rn rt
# verified: signed offset: b24=1 b23=0; pre: b24=1 b23=1; post: b24=0 b23=1
# non-temporal (stnp/ldnp): b24=0 b23=0 -- same plain-offset semantics here
for opc_base, l, mn, sfx, nb in ((0b00, 0, "st", "w", 4), (0b00, 1, "ld", "w", 4),
                                 (0b10, 0, "st", "x", 8), (0b10, 1, "ld", "x", 8)):
    sh = nb.bit_length() - 1
    for b24v, b23v, modenm in ((1, 0, "so"), (0, 0, "so"), (1, 1, "pr"), (0, 1, "po")):
        pat = ("rt, rt2, rn, imm7 is size2=%d & s29=1 & f28_27=1 & b26=0 & b25=0 & b24=%d "
               "& op23=%d & b22=%d & imm7:imm7 & rt2:rt2 & rn:rn & rt:rt"
               % (opc_base, b24v, b23v, l))
        off = "(sext(imm7, 7) << %d)" % sh
        ze = "" if nb == 8 else ", 32"
        if mn == "st":
            body = f"*(rn + {off}) = zext(rt); *(rn + {off} + {nb}) = zext(rt2);"
        else:
            body = (f"rt = zext(load(rn + {off}, {nb}){ze}); "
                    f"rt2 = zext(load(rn + {off} + {nb}, {nb}){ze});")
        ctor(f"{mn}{sfx}_{modenm}", pat, body)

# ------------------------------------------------- adr/adrp
emit("")
emit("// ===================== adr/adrp =====================")
ctor("adr", "rd, imm19 is sf31=0 & f28_24=0b10000 & imm19:imm19 & rd:rd",
     "rd = inst_start + sext(imm19 << 2, 21);")
ctor("adrp", "rd, imm19 is sf31=1 & f28_24=0b10000 & imm19:imm19 & rd:rd",
     "rd = ((inst_start >> 12) << 12) + sext(imm19 << 14, 33);")

text = "\n".join(OUT) + "\n"
if len(sys.argv) > 1:
    with open(sys.argv[1], "w") as f:
        f.write(text)
    print(f"wrote {sys.argv[1]}: {len(OUT)} lines")
else:
    sys.stdout.write(text)
